/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#include "stm32h7xx.h"

#include "systick.h"
#include "gpio.h"
#include "i2c.h"
#include "rcc.h"
#include "spi.h"
#include "usart.h"

#include "FreeRTOS.h"
#include "task.h"

#include "apps/led/led_task.h"
#include "apps/net/net_task.h"
#include "apps/common_net_interface/common_net_interface_task.h"
#include "apps/pms5003/pms5003_task.h"
#include "apps/terminal/terminal_task.h"
#include "apps/measure/measure_task.h"

static void main_freertos_irq_cb(void)
{
#if !defined(NO_ETH)
	extern void HAL_IncTick(void);
	HAL_IncTick();
#endif // !NO_ETH

	if(xTaskGetSchedulerState() == taskSCHEDULER_RUNNING) {
		xPortSysTickHandler();
	}
}

static void boot_task(void *parameter)
{
	// Start critical tasks
	led_task_initialise();
	terminal_task_initialise();

	// Start tasks
#if !defined(NO_ETH)
	net_task_initialise();
#endif // !NO_ETH
	cni_task_initialise();
	measurenet_task_initialise();

	vTaskDelete(NULL);
}

int main(void)
{
	SystemInit();
	SystemCoreClockUpdate();

#if !defined(NO_ETH)
	extern void HAL_Init(void);
	HAL_Init();
#endif // !NO_ETH

	// Drivers init
	rcc_init();
	systick_init();
	gpio_init();
	i2c_init_master(I2C2, I2C_TIMING_STANDARD_100KHZ);
	i2c_init_master(I2C4, I2C_TIMING_STANDARD_100KHZ);

	// Register callback
	systick_irq_add_callback(main_freertos_irq_cb);

	#define STACK_SIZE_BOOT 512
	static StaticTask_t xTaskBuffer;
	static StackType_t xStack[STACK_SIZE_BOOT];
	xTaskCreateStatic(boot_task, "BOOT", STACK_SIZE_BOOT, NULL, 1, xStack, &xTaskBuffer);

	// Start OS
	vTaskStartScheduler();

    // Loop forever
	for(;;);
}
